#!/usr/bin/env node
/**
 * split-i18n.js — Extracts each language block from data/i18n-source.js (the
 * canonical source of truth) into separate files under js/i18n/<lang>.js.
 * This lets the runtime ship only the language the user actually needs
 * (~16 KB) instead of all 8 (~130 KB), with lazy-loading on language switch.
 *
 * The generated per-lang file is a tiny side-effect script:
 *   (window.__I18N_DATA__ = window.__I18N_DATA__ || {})['en'] = { ... };
 *
 * Run after editing data/i18n-source.js (canonical strings):
 *   node scripts/split-i18n.js
 */

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const SOURCE    = path.join(ROOT, 'data', 'i18n-source.js');
const OUT_DIR   = path.join(ROOT, 'js', 'i18n');

const src = fs.readFileSync(SOURCE, 'utf8');

// Find the `const I18N = {` opening and walk braces to locate its closing `};`.
const openIdx = src.indexOf('const I18N = {');
if (openIdx === -1) throw new Error('Could not find `const I18N = {` in data/i18n-source.js');

let depth = 0, i = openIdx + 'const I18N = '.length, closeIdx = -1;
for (; i < src.length; i++) {
  const ch = src[i];
  if (ch === '{') depth++;
  else if (ch === '}') {
    depth--;
    if (depth === 0) { closeIdx = i; break; }
  }
}
if (closeIdx === -1) throw new Error('Unbalanced braces in I18N object');

// Body between the outer `{` and `}` — contains `en: { ... }, 'pt-BR': { ... }, ...`
const bodyStart = src.indexOf('{', openIdx) + 1;
const body      = src.slice(bodyStart, closeIdx);

// Walk top-level lang entries.
// Each entry looks like:   <key>: { ... },   where key is `en` or `'pt-BR'`.
const langs = [];
let j = 0;
while (j < body.length) {
  // Skip whitespace, commas, newlines
  while (j < body.length && /[\s,]/.test(body[j])) j++;
  if (j >= body.length) break;

  // Read the key (bareword or quoted)
  let key = '';
  if (body[j] === "'" || body[j] === '"') {
    const quote = body[j++];
    while (j < body.length && body[j] !== quote) key += body[j++];
    j++; // consume closing quote
  } else {
    while (j < body.length && /[a-zA-Z0-9_-]/.test(body[j])) key += body[j++];
  }

  // Skip `:` and whitespace
  while (j < body.length && /[\s:]/.test(body[j])) j++;
  if (body[j] !== '{') throw new Error(`Expected '{' after key '${key}' at offset ${j}`);

  // Walk until matching `}`
  const valStart = j;
  let d = 0;
  for (; j < body.length; j++) {
    const ch = body[j];
    if (ch === '{') d++;
    else if (ch === '}') {
      d--;
      if (d === 0) { j++; break; }
    }
    // Skip string contents to avoid counting braces inside strings
    else if (ch === "'" || ch === '"' || ch === '`') {
      const quote = ch;
      j++;
      while (j < body.length && body[j] !== quote) {
        if (body[j] === '\\') j++; // escape
        j++;
      }
    }
  }
  const valEnd = j;
  const obj = body.slice(valStart, valEnd);
  langs.push({ key, obj });
}

if (!langs.length) throw new Error('No language entries found.');

fs.mkdirSync(OUT_DIR, { recursive: true });

const header =
  '/* Auto-generated by scripts/split-i18n.js — DO NOT EDIT BY HAND.\n' +
  '   Source: data/i18n-source.js. Modify there, then re-run the script.\n' +
  '   This file lazy-loads a single language to keep the initial payload small. */\n';

for (const { key, obj } of langs) {
  const safeKeyJs = JSON.stringify(key); // "'pt-BR'" → '"pt-BR"'
  const out =
    `${header}` +
    `(window.__I18N_DATA__ = window.__I18N_DATA__ || {})[${safeKeyJs}] = ${obj};\n`;
  const fileName = key + '.js';
  fs.writeFileSync(path.join(OUT_DIR, fileName), out, 'utf8');
  const sizeKB = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1);
  console.log(`  js/i18n/${fileName.padEnd(10)}  ${sizeKB.padStart(6)} KB`);
}

console.log(`\nDone. Generated ${langs.length} language files in js/i18n/.`);
